### ISSUE TITLE
Thoughts

### ISSUE THREAD

**Issue by jpillora** [anacrolix/args#1]
Hey matt, I have thoughts on this! And was thinking of making my own bare bones arg parser for https://github.com/jpillora/opts. Not sure if this is useful this this module, though I thought I'd post here anyway https://github.com/jpillora/opts/issues/31 (I just wrote this now since you jogged my memory)

**Comment by anacrolix** [comment]
@jpillora I was inspired to have another go at arg parsing after discovering https://github.com/jpillora/opts recently, as I had just started to prefer https://github.com/alexflint/go-arg to my own https://github.com/anacrolix/tagflag. FWIW, this repo doesn't intend to do what I think you mean by bare bones parsing, but I intended actually to have this one drive parsing using normal Go control flow. So subcommands don't run their parsers until they're actually ran, and parsing occurs left to right only. All I've found so far is it's easier to have jumbo structs like param instead of 10 different interfaces for each of Flag, Subcommand, Option, etc, and that it's probably necessary to defer the main execution by default during parsing otherwise you start executing stuff in subcommands that take a long time only to discover that the rest of the arguments were invalid when you get to them.

Another insight I had before starting this was that it's easier to couple arg declaration, and actual value management in Go, the type system just isn't advanced enough to declare complex parsers and then support instantiating them as a separate step, hence doing parsing as part of the control flow.

Here's an example of use in its current state https://github.com/anacrolix/torrent/blob/master/cmd/torrent/main.go#L226-L277.

This is what I'd much rather have but I don't know if Go is up to it: https://github.com/clap-rs/clap.

**Comment by jpillora** [comment]
Ah nice, opts sub commands works - though it’s not as clean as I’d like it
to be. The example looks pretty good 👍 what’s the use case for lazy
parsing? RE simple type system, yep i had to squeeze all logic into struct
tags which means run time “compilation”
